/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <math.h>
#include "com_example_urovo_dotorom_jnitest_MainActivity.h"

/*
 * Class:     com_example_urovo_dotorom_ndksample_MainActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_urovo_1dotorom_jnitest_MainActivity_getStringFromNative
  (JNIEnv *env, jobject obj){
        return (*env)->NewStringUTF(env,"Hello From JNI.....");
  }

JNIEXPORT jint JNICALL Java_com_example_urovo_1dotorom_jnitest_MainActivity_NumAdd
        (JNIEnv  *env,  jclass obj, jint a, jint b){

    jint jsum;

    //jsum=a+b;
    jsum=pow(a,b);

    return jsum;
}
