/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "com_example_urovo_dotorom_jniadd_MainActivity.h"

/*
 * Class:     com_example_urovo_dotorom_ndksample_MainActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_urovo_1dotorom_jniadd_MainActivity_getStringFromNative
  (JNIEnv *env, jobject obj){
        return (*env)->NewStringUTF(env,"Hello From JNI.....");
  }

